
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: postgres
  port: 5432
  host: localhost

development:
  <<: *default
  database: online_learning

test:
  <<: *default
  database: test_online_learning

production:
  <<: *default
  database: online_learning
